"""change password
 header

Revision ID: 847680887fa2
Revises: 8df46d4a3bf0
Create Date: 2023-06-05 16:34:22.339588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847680887fa2'
down_revision = '8df46d4a3bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
