"""update to orders table (purchased)

Revision ID: a5e813023889
Revises: 847680887fa2
Create Date: 2023-06-06 10:57:30.871149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e813023889'
down_revision = '847680887fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=True))
        batch_op.drop_column('purchase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
